#!/usr/bin/env sh

# =============================================================================
# To be sourced from .zshenv
# =============================================================================

# XDG
# -----------------------------------------------------------------------------
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_BIN_HOME="$HOME/.local/bin" # NOT STANDARD

XDG_FOLDERS=(
    "$XDG_CONFIG_HOME"
    "$XDG_DATA_HOME"
    "$XDG_STATE_HOME"
    "$XDG_CACHE_HOME"
    "$XDG_BIN_HOME"
)
for i in "${XDG_FOLDERS[@]}"; do
    [ ! -d "$i" ] || mkdir -p "$i"
done
unset XDG_FOLDERS


# Helper variables
# -----------------------------------------------------------------------------
OS="$(/usr/bin/uname -s)"
case "$OS" in
    Linux*)     export OS=linux;;
    Darwin*)    export OS=macos;;
    CYGWIN*)    export OS=windows;;
    MINGW*)     export OS=windows;;
esac

# Apple sillicon will use arm64, intel is x86_64
ARCH="$(/usr/bin/uname -m)"
export ARCH

case "$SHELL" in
    *zsh)   export USING_SHELL=zsh;;
    *bash)  export USING_SHELL=bash;;
    *dash)  export USING_SHELL=dash;;
    *)      export USING_SHELL="$SHELL";;
esac

